export default Object.freeze({
  BACHECA: "Bacheca",
  INFOLIBRO: "InfoLibro",
  CREAZIONEBC: "CreazioneBC",
  ACCEDI: "Login",
  REGISTRATI: "Register",
  UTENTIDAINVITARE: "Inviti",
  INFOBOOKCLUBF: "infoBCFounder",
  INFOBOOKCLUBU: "infoBCUtente",
  REVISIONEINVITI: "BCInvites",
  CHISIAMO: "ChiSiamo",
  SICUREZZA: "Sicurezza",
  INVITAUTENTI: "InvitaUtenti",
  CATALOGO: "Catalogo",
  CLUBS: "Clubs",
  RICERCA: "Ricerca",
});
